# coverage:
#   status:
#     changes: false
#     default_rules:
#       flag_coverage_not_uploaded_behavior: "include"
#     patch:
#       default:
#         base: "auto"
#         if_ci_failed: "error"
#         only_pulls: true
#         target: 50
#     project:
#       default:
#         if_ci_failed: "error"
#         only_pulls: true
#         target: "auto"
flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - carryforward: true
      name: x
    - carryforward: true
      name: y
    - carryforward: true
      name: z

# cli:
#   plugins:
#     pycoverage:
#       path_to_coverage_file: '.artifacts/.coverage'
#       report_type: "json"
